[package]
name = "apps-ports"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "apps-ports"
path = "src/main.rs"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
crossterm = "0.27"
tabled = "0.15"
